FROM node:bookworm-slim

ENV PUBLIC_MAPBOX_ACCESS_TOKEN=$PUBLIC_MAPBOX_ACCESS_TOKEN
ENV PUBLIC_GOOGLE_API_KEY=$PUBLIC_GOOGLE_API_KEY
ENV PUBLIC_BACKEND_ORIGIN=$PUBLIC_BACKEND_ORIGIN
ENV PUBLIC_KRATOS_ORIGIN=$PUBLIC_KRATOS_ORIGIN

RUN corepack enable
COPY . .
RUN pnpm install
RUN pnpm build
CMD ["node", "build"]